### ISSUE TITLE
SyntaxError: Unexpected strict mode reserved word

### ISSUE THREAD

**Issue by Baskerville42** [IanVS/sails-hook-jsonapi#2]
When I try to lift app in `development` mode I get this error
```bash
/usr/local/bin/node app.js
error: /Users/baskerville42/WebstormProjects/toprovidepr-site/toprovidepr-backend/node_modules/sails-hook-jsonapi/lib/hook.js:5
  let moduleUtils = require('./utils/module-utils');
  ^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/baskerville42/WebstormProjects/toprovidepr-site/toprovidepr-backend/node_modules/sails-hook-jsonapi/index.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/baskerville42/WebstormProjects/toprovidepr-site/toprovidepr-backend/node_modules/sails/lib/hooks/moduleloader/index.js:432:26
    at /Users/baskerville42/WebstormProjects/toprovidepr-site/toprovidepr-backend/node_modules/sails/node_modules/lodash/dist/lodash.js:3741:15 [SyntaxError: /Users/baskerville42/WebstormProjects/toprovidepr-site/toprovidepr-backend/node_modules/sails-hook-jsonapi/lib/hook.js:5
  let moduleUtils = require('./utils/module-utils');
  ^^^
Unexpected strict mode reserved word]

Process finished with exit code 0
```

**Comment by Baskerville42** [comment]
But in `production` mode it's all right

**Comment by IanVS** [comment]
What version of node are you using?  Initially I was using `let`, but replaced most of them with `var` in https://github.com/IanVS/sails-hook-jsonapi/commit/cf6dfc1d647ff16dae40f501c5d77e615e971fc3.  Apparently I missed a few.

**Comment by Baskerville42** [comment]
``` bash
$ node -v
v0.12.9
$ npm -v
3.5.3
```

**Comment by IanVS** [comment]
Would you like to submit a PR to change `let` to `var` in that file?  Or, you can install node 4 or above.  If you'd rather not do either, I can make a fix within a few days.

**Comment by listepo** [comment]
Fixed see https://github.com/listepo/sails-hook-jsonapi/commit/4071a6fa93aa00fa306a8cdb9241633507d6a25b

**Comment by IanVS** [comment]
Thanks!
